import './globals.css'
import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'

const font = IBM_Plex_Sans({ subsets: ['latin'] ,
weight: ['400', '500' , '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`flex items-center justify-center h-screen  bg-[url('/bg.svg')] bg-cover bg-no-repeat ${font.className} `}>{children}</body>
    </html>
  )
}
